### ISSUE TITLE
Çok fazla öneri veriliyor.

### ISSUE THREAD

**Issue by ahmetaa** [COMU/zemberek-extension#1]
Öneri sayısı bazen yirmi-otuz olabiliyor ve bu rahatsız ediyor.
ZemberekSpellCheck sınıfında önerilerin elde edildiği yere bir kısıtlama koyalım. şimdilik 7'den fazla sonuç gelirse 7 olacak şekilde kısıtlanabilr. 

@COMU/zemberek

**Comment by talhakanyilmaz** [comment]
Selamlar,
Şu şekilde yaptım, istediğimiz şekilde çalıştı. Uygunsa gönderiyorum.

`if((spellChecker.suggestForWord(s)).size() > 7) return spellChecker.suggestForWord(s).subList(0,7);
 else return spellChecker.suggestForWord(s);`

**Comment by ahmetaa** [comment]
Güzel.
Ama bir iyileştirme yapılabilir, iki kez suggestForWord(s) çağrılıyor. Bu nispeten masraflı bir işlem. Önce onun sonucunu `List<String>` olarak alıp onu ya da sublist değerini döndürmek daha iyi.

**Comment by ahmetaa** [comment]
Kodu düzenledikten sonra "format" ile indentation vs düzenlemen iyi olur. IDE kullanıyorsan bunun için Code->ReformatCode seçebilirsin.

**Comment by ahmetaa** [comment]
Spam oldu, bu şekilde yaptıktan sonra kodu yollayabilirsin. Gerekirse sonra düzenlenir.
