### ISSUE TITLE
Eklentinin windows ile denenmesi.

### ISSUE THREAD

**Issue by ahmetaa** [COMU/zemberek-extension#10]
Henüz hiç windows üzerinde denenmedi.

**Comment by okanozdemir** [comment]
Eklentiyi **Windows 10 Pro x64 Sürüm: 1803** üzerinde **LibreOffice Sürüm: 6.1.2.1 (x64)** ile denedim. İlk seferde sorunsuz yüklendi ve çalıştı. Her açılışta yazmaya başladıktan sonra 3-4 saniyelik bir yanıt vermeme durumu var. Denemeyi yüksek performanslı fiziksel bir makine üstünde gerçekleştirdim.

**Comment by okanozdemir** [comment]
Aynı sistem üzerinde **LibreOffice Sürüm: 5.4.7.2 (x64)** ile de denedim. Aynı yanıt vermeme durumu dışında yükleme ve çalıştırma sorunsuz.

**Comment by ahmetaa** [comment]
Okan teşekkürler. Bu başlangıçtaki gecikme durumu hem JRE hem de asıl zemberek'in ilklendirilmesi gecikmesinden kaynaklanıyor. Bunu şimdililk kurulum dokümanına not olarak yazabiliriz. Gecikmeyi azaltmak için ne yapabiliriz bakacağım. İstersen bu işi kapatabilirsin.
