### ISSUE TITLE
İlk sürümün oluşturulması ve oxt dosyasının "release" bölümüne eklenmesi

### ISSUE THREAD

**Issue by ahmetaa** [COMU/zemberek-extension#15]
İlk deneme sürümünün yayınlanması mümkün diye düşünüyorum. Bu konuda ne dersiniz?

Aklıma gelen yapılacak işler
- Release için oxt hazırlayıp "releases" alanına muhtemelen "0.1.0-preview" sürüm numarası ile eklentiyi koymak
- Yayınlanmadan önce gerçek dokümanlarla biraz test yapmak.

#7 ve #13 sonraki sürüme bırakılabilir.

**Comment by okanozdemir** [comment]
Birkaç uzun döküman ile test yaptım bildiğimiz sorunlar dışında bir hataya rastlamadım. Okulda daha kalabalık bir ekipten deneme yapmalarını rica edebiliriz ama.

**Comment by ahmetaa** [comment]
Sağol Okan. Bence ilk sürüm için yeterli. Ben bir iki değişiklik yapıyorum. Sonra release için oxt dosyasını siteye koyabiliriz. Ben takrar yazacağım.

**Comment by ahmetaa** [comment]
@okanozdemir tamamdır. Çok önemli olmayan bir değişiklik yaptım, sorun yok gibi. Eğer herkes için de uygunsa release alanına v0.1.0 olarak tag oluşturup güncellemeden sonra ürettiğin oxt dosyasını da aynı yere upload edebilirsin.

**Comment by ahmetaa** [comment]
Release alanı derken şurayı kastettim:
https://github.com/COMU/zemberek-extension/releases

**Comment by okanozdemir** [comment]
Şimdi bir sorun fark ettim. Bazı sayılara kesme işareti ile gelen bazı ekler yanlış olarak işaretleniyor. Kesme işareti kullanılmadığında doğru işaretleniyor.

Örneğin:
```
63'ü -> Yanlış
63ü -> Doğru
```
Bunun için yeni bir iş mi oluşturalım ?

**Comment by ahmetaa** [comment]
Evet lütfen. Rakamlar ile ilgili çalışma gerekecek. Ama yine de ilk release yapalım derim.

**Comment by okanozdemir** [comment]
Sanıyorum halloldu. Sorun yoksa kapatıyorum bu işi ?

**Comment by ahmetaa** [comment]
Sağol Okan kapatabilirsin. İlk sürüm hayırlı olsun, bence iyi bir iş ortaya çıktı, herkese çok teşekkürler. 
@COMU/zemberek : isteyenler ilk sürümü duyurabilir. Test yapanlardan geri dönüş olur diye umuyorum.
