### ISSUE TITLE
Eklentinin çalışması için libreoffice-dev kurulumu zorunlu mu?

### ISSUE THREAD

**Issue by ahmetaa** [COMU/zemberek-extension#4]
İş yerinde yaptığım testte LO 5 ile eklentiyi yüklemeye çalıştığımda LO java sınıflarını bulamadığını söyledi. Acaba LO5 ve 6 için libreoffice-dev kurulmadan eklenti yüklenebiliyor mu deneyinin yapılması gerekiyor. 

@COMU/zemberek

**Comment by okanozdemir** [comment]
Sanal makineye LibreOffice 6.1.2.1 10(Build:1) kurup eklentiyi yükledim. İlk yazmaya başladığımda uygulama hata mesajı vermeden kırıldı. Bir kaç kez uygulamayı yeniden başlatıp eklentiyi tekrar yükleyince sorunsuz çalışmaya başladı. 

Daha sonra LibreOffice 5.4.1.1 kurup eklentiyi yükledim. LO'yu ilk çalıştırmamda JRE'nin bulunamadığına dair hatalar çıktı ama program açıldı. Eklentiyi yüklemeyi denediğimde söylediğinize benzer bir hata aldım. JRE'yi yükledikten sonra eklentiyi yüklemeyi denediğimde ilk önce uygulama hata mesajı vermeden kırıldı. Yine bir kaç kez yeniden başlatma ve eklentiyi silip yükleme işleminden sonra çalışmaya başladı. Şimdi de eğer eklenti yüklüyse LO açıldıktan sonra 3-4 saniye kadar donuyor. Daha sonra sorunsuz şekilde istenen işlemleri yapabiliyor.

[Konsol Mesajları](https://i.hizliresim.com/LDkyWb.png)

Ekran görüntüsündeki son mesaj geldikten sonra LO yanıt vermeye başlıyor ve eklenti çalışıyor.

**Comment by ahmetaa** [comment]
Teşekkürler Okan. JRE ve OS sürüm ve türünü de yazabilir misin?

Kullanıcı deneyimi açısından problemli bir konu bu. Eski OpenOffice eklentisi ile de benzeri şeyler yaşanmıştı maalesef. Bu tür problemleri en aza indirmek için çalışma yapmamız gerekecek. 

İlk durumda neden kırılma yaşandığını bilemiyorum. LO için bir tür hata logu vs üretiliyor mu araştırabilir misin?

İkinci durumda LO açılışından sonra 3-4 saniye beklemesinin nedeni zemberek başlangıcının zaman alması. Bunu ne kadar azaltabiliriz bilmiyorum ama sanal makinede olduğu için normalden biraz daha fazla zaman almış olabilir. Bu konuda ayrıca bir çalışma yaparız.

Gönderdiğin ekran görüntüsünden anladığım kadarıyla zemberek sözlük serialization  için kullandığımız protocol-buffers kütüphanesi problemli bir reflection işlemi içeriyor. Bunun nedeni ve çözümüne bakacağım. 

Ama anladığım kadarı ile "libreoffice-dev kurulumu zaruri değil.

**Comment by okanozdemir** [comment]
LO 6'da herhangi bir gecikme olmazken LO 5'de söylediğim gibi bir gecikme vardı. LO 6 için daha önce log ürettirmeyi denemiştim ancak kırılmanın sebebini oradan bulamamıştım en kısa sürede tekrar bakacağım ona. Kullanıcı tarafından elle çalıştırılmadığı sürece log üretmiyor sanırım.

LO 6'yı Ubuntu'nun repolarından kurdum. LO 5'i siteden deb paketi olarak indirip kurdum. İkisinde de libreoffice-dev kurulumu yapmadım.

**OS**
`Ubuntu 18.04.1`

**JRE**
```
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3, mixed mode)
```

**Comment by ahmetaa** [comment]
Detaylı açıklama için teşekkürler Okan. 
"dev" paketinin kurulmasının gerekmediği anlaşıldığı için bu problemi kapatıyorum şimdilik. 

Protobuf ile ilgili warning bililnen bir konu imiş ama kırılmaya yol açmayacağı söyleniyor. ( https://github.com/protocolbuffers/protobuf/issues/3781 ) Sen Java 10 kullandığın için bu warning görünüyor.

Açılışın biraz yavaş olması ile ilgili konuda neler yapılabileceğine bakacağım. Spell checker initializationu da maalesef biraz yavaş ve çok fazla bellek tüketiyor.
