### ISSUE TITLE
Zemberek 0.16.0 derlenmesi ve eklenti jar dosyasının güncellenmesi

### ISSUE THREAD

**Issue by ahmetaa** [COMU/zemberek-extension#6]
Zemberek 0.16.0 derleyip proje lib içerisine yerleştirilmesi gerekiyor.

**Comment by okanozdemir** [comment]
Zemberek 0.16.0'ın Jar paketini oluşturamıyorum. zemberek-core testlerinde hata oluşuyor. 

```
Tests in error: 
  getTest(zemberek.core.collections.UIntIntMapTest): zemberek/core/collections/UIntIntMap
  removeTest(zemberek.core.collections.UIntIntMapTest): zemberek/core/collections/UIntIntMap
  getSetTest(zemberek.core.collections.SparseFloatMatrixTest): zemberek/core/collections/SparseFloatMatrix
```

**Comment by ahmetaa** [comment]
Bu şaşırtıcı. Projeyi güncelledin mi? Güncelledikten sonra sağdaki maven alanında zemberek-nlp/Lifecyce sekmesinde clean ve test tasklarını işletmeyi deneyebilir misin?

**Comment by ahmetaa** [comment]
COMU içindeki zemberek klonunu mu kullanıyorsun? Eğer öyleyse oraya değişiklikleri aktarmamız gerekir.

**Comment by okanozdemir** [comment]
Yok kendi profilimdeki klonu kullanıyordum ve güncellemiştim. Sadece compile ve package'ı çalıştırmıştım. Şimdi clean ve test'i yapıp compile ve package'ı çalıştırdım sorun çıkmadı, zemberek-full.jar oluştu.

**Comment by ahmetaa** [comment]
Büyük güncellemeler sonrası bazen bu tür problemler olabiliyor maalesef. Eğer projeye eklediysen bu işi  kapatabilirsin.
