### ISSUE TITLE
Kurulum dokümanının yazılması

### ISSUE THREAD

**Issue by ahmetaa** [COMU/zemberek-extension#9]
Muhtemelen ilk alfa sürümü öncesi bir kurulum dokümanı yazılması iyi olur. Kökte bulunan README.md içerisine ya da libreoffice-tr-tools dizini içine eklenecek bir README.md içerisine yazabiliriz.

- Java kontrolü ve kurulumu
- Libre office eklentisinin nereden indirileceği ve nasıl kurulacağı (ekran görüntüleri ile). Ekran görüntülerini de proje içerisinde oluşturacağımız "site"  adlı bir dizine ekleyebiliriz. 
- Uyarılar ve sorumluluk reddi
- Olası problemler

Sonradan doküman daha uygun bir yere de aktarılabilir.

**Comment by ahmetaa** [comment]
Doküman Türkçe olacak.
@talhakanyilmaz @okanozdemir biriniz bu konuyu almak ister misiniz?

**Comment by talhakanyilmaz** [comment]
Bununla ben ilgilenebilirim.

**Comment by ahmetaa** [comment]
Bu arada indirme bağlantısını şimdilik boş bırakabiliriz. Onun için proje alanında bir release linki veririz herhalde.

**Comment by talhakanyilmaz** [comment]
Benim 2 sorum var.
1. Kaynak koddan oxt dosyasını elde etmek için gereken adımları da ekleyelim mi yoksa sadece hazır oxt dosyasının nasıl ekleneceğini açıklamak yeterli mi şimdilik?
2. Lisans konusunda ne düşünüyoruz? Dokümana lisans ile ilgili de bir not eklense iyi olur sanırım.

**Comment by ahmetaa** [comment]
1. Bu kullanıcı dokümanı olduğu için İlk etapta sadece hazır oxt dosyasının indirilmesi olsun
2. Lisans konusunda ise nihai bir karar vermemiz gerekiyor. 
Apache2 - zemberek nlp proje lisansı
MPL - Libre Office lisansı
GPL2 - Popüler FOSS lisansı. 

Bana hepsi uyar. 

@mdakin @nyucel ne dersiniz?
@talhakanyilmaz ve @okanozdemir  sizin de görüşleriniz varsa lütfen yazın

**Comment by ahmetaa** [comment]
Binary için CC türü lisanslar da olabilir tabi.

**Comment by mdakin** [comment]
Apache2 uygundur bence, lisanslar konusunda cok derin bilgim yok, belki @nyucel daha iyi bir yorum yapabilir.

**Comment by nyucel** [comment]
LibreOffice projesinin lisanslarına uygun seçersek iyi olur diye düşünüyorum. Onlar MPLv2/LGPLv3+ ikili lisanslamasını kullanıyorlar.

**Comment by ahmetaa** [comment]
Talha eline sağlık, güzel iş çıkarmışsın. Bir iki düzeltme önereceğim

- Başlığı ve eklentinin resmi adını "Zemberek-Extension" yerine "LibreOffice Türkçe Dil Araçları" yapsak daha mı iyi olur diye düşündüm. Bunun nedeni önceden Zemberek isminde bir Libre Office eklentisi vardı, isimlerin karışmasını engelleme adına. 

- Java kurulumunda **openjdk-8-jdk** yerine **openjdk-8-jre** daha iyi olabilir. Bu daha küçük bir kurulum oluyor. Ayrıca "sudo apt-get" Ubuntu'ya özel. Bunu belirtmekte yarar var. 

- java --version denildiğinde uygun Java kurulu ise ekranda görünecek sonuç yazılabilir.

- Olası sorunlar kısmında Bunun erken deneme sürümü olduğunu belirtmekte yarar var. Hataların olabileceği belirtilmeli.

**Comment by ahmetaa** [comment]
@nyucel  Tamam hocam, bence sorun yok, MPLv2 lisansını ekledim.
